language: csharp
dist: xenial
sudo: required
mono: none
dotnet: 2.2
solution: Project\ Stable.sln
script:
  - dotnet restore
  - dotnet build -c Release
  - cd StableAPIHandler\ Tests
  - dotnet test
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
