language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1.200
solution: Project\ Stable.sln
before_script:
  - dotnet restore
script:
  - dotnet build -c Release
  - cd StableAPIHandler\ Tests
  - dotnet test
